export const environment = {
  production: false,
  apiUrl_Estabelecimento: 'http://localhost:3333/api/estabelecimentos',
  apiUrl_cnae: 'http://localhost:3333/api/cnae',
  apiUrl_Ativiades: 'http://localhost:3333/api/atividades',
  apiUrl_Protocolos: 'http://localhost:3333/api/protocolos',
  apiUrl_pdfProtocolo: 'http://localhost:3333/api/getprotocolo/',
  apiUrl_pdfRelatorio: 'http://localhost:3333/api/pdf/relatorios/',
  apiUrl_pdfTermo: 'http://localhost:3333/api/pdf/termos/',
  apiUrl_Login: 'http://localhost:3333/api/login',
  apiUrl_pdfLicenca: 'http://localhost:3333/api/licenca/',
  apiUrl_Denuncias: 'http://localhost:3333/api/denuncias',
  apiUrl_Anexos: 'http://localhost:3333/api/anexos',
  apiUrl_Anexos2: 'http://localhost:3333/api/files',
  apiUrl_Licencas: 'http://localhost:3333/api/licencas',
  apiUrl_LicencasPost: 'http://localhost:3333/api/licencas',
  apiUrl_Embasamento: 'http://localhost:3333/api/embasamentos',
  apiUrl_Documentos: 'http://localhost:3333/api/documentos',
  apiUrl_Usuarios: 'http://localhost:3333/api/usuarios',
  apiUrl_Termo: 'http://localhost:3333/api/termos',
  apiUrl_Relatorio: 'http://localhost:3333/api/relatorios',
  apiUrl_sendTermo: 'http://localhost:3333/api/pdf/email/termo',
  apiUrl_sendLicenca: 'http://localhost:3333/api/pdf/email/licenca',
  apiUrl_sendRelatorio: 'http://localhost:3333/api/pdf/email/relatorio',
  apiUrl_sendProtocolo: 'http://localhost:3333/api/pdf/email/protocolo',
};

