export const environment = {

  production: true,
  apiUrl_Licencas: 'https://sis-visa-api.herokuapp.com/api/licencas',
  apiUrl_LicencasPost: 'https://sis-visa-api.herokuapp.com/api/licencas',
  apiUrl_Estabelecimento: 'https://sis-visa-api.herokuapp.com/api/estabelecimentos',
  apiUrl_cnae: 'https://sis-visa-api.herokuapp.com/api/cnae',
  apiUrl_Ativiades: 'https://sis-visa-api.herokuapp.com/api/atividades',
  apiUrl_Protocolos: 'https://sis-visa-api.herokuapp.com/api/protocolos',
  apiUrl_pdfProtocolo: 'https://sis-visa-api.herokuapp.com/api/getprotocolo/',
  apiUrl_pdfRelatorio: 'https://sis-visa-api.herokuapp.com/api/pdf/relatorios/',
  apiUrl_pdfTermo: 'https://sis-visa-api.herokuapp.com/api/pdf/termos/',
  apiUrl_pdfLicenca: 'https://sis-visa-api.herokuapp.com/api/licenca/',
  apiUrl_Login: 'https://sis-visa-api.herokuapp.com/api/auth/sign-in',
  apiUrl_Denuncias: 'https://sis-visa-api.herokuapp.com/api/denuncias',
  apiUrl_Anexos: 'https://sis-visa-api.herokuapp.com/api/anexos',
  apiUrl_Anexos2: 'https://sis-visa-api.herokuapp.com/api/files',
  apiUrl_Embasamento: 'https://sis-visa-api.herokuapp.com/api/embasamentos',
  apiUrl_Documentos: 'https://sis-visa-api.herokuapp.com/api/documentos',
  apiUrl_Usuarios: 'https://sis-visa-api.herokuapp.com/api/usuarios',
  apiUrl_Termo: 'https://sis-visa-api.herokuapp.com/api/termos',
  apiUrl_Relatorio: 'https://sis-visa-api.herokuapp.com/api/relatorios',
  apiUrl_sendTermo: 'https://sis-visa-api.herokuapp.com/api/pdf/email/termo',
  apiUrl_sendLicenca: 'https://sis-visa-api.herokuapp.com/api/pdf/email/licenca',
  apiUrl_sendRelatorio: 'https://sis-visa-api.herokuapp.com/api/pdf/email/relatorio',
  apiUrl_sendProtocolo: 'https://sis-visa-api.herokuapp.com/api/pdf/email/protocolo',
}
